name: core-lib-actions
run-name: Core-Lib Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-core-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: ./packages/core-lib
          build-dir: ./packages/core-lib/build
          generator: Ninja
          cxx-compiler: clang++

      - name: Tar build files
        run: tar -cvf build_files.tar -C ./packages/core-lib build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: core-lib-build-output
          path: build_files.tar
          retention-days: 1

  test-core-lib:
    needs: build-core-lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: core-lib-build-output
          path: ./packages/core-lib

      - name: Extract Tar Files
        run: tar -xvf ./packages/core-lib/build_files.tar -C ./packages/core-lib/

      - name: Test Core-Lib
        run: cd ./packages/core-lib/build/tests && ctest

  deploy-backend:
    needs: test-core-lib
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: Bounceapp/render-action@0.12.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          service-id: srv-d6hie0hdrdic73cnd990
          retries: 20
          wait: 16000
          sleep: 30000

  deploy-frontend:
    needs: test-core-lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v41.1.4
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          vercel-args: --prod